CONST_INT_WIDTH = 640
CONST_INT_HEIGHT = 480
CONST_INT_WAIT_COUNT = 50
CONST_INT_MAXIMUM = 999999999
CONST_INT_BOUNDARY_SALAD = 145
CONST_INT_BOUNDARY_SANDWICH = 280

CONST_TUPLE_COLOR = (0, 0, 255)

CONST_STR_SALAD = 'SALAD'
CONST_STR_SANDWICH = 'SANDWICH'

CONST_DICT_STATUS = {
    0: "init",
    1: "tracking",
    2: "done"
}

CONST_DICT_MENU = {
    0: "",
    1: "",
    2: CONST_STR_SANDWICH,
    3: CONST_STR_SALAD
}